### ISSUE TITLE
were is the world.json?

### ISSUE THREAD

**Issue by LogicViper** [dig/onset-world#2]
this one is confusing  because you need to use the world.json but its not in the file pack also the map editor files are called like this

map_Prison_Gate_04_38_Sun_Jan.ini
map_Prison_Gate_04_38_Sun_Jan.lua

end nowere is explained what to do

**Comment by dig** [comment]
Hi, you are using the old map editor which exports to ini/lua. My editor/world packages do not support the old format, we are json only. If you use the updated editor (which comes with the server by default), it will generate a world.json in the root server directory when the world is saved. You can download the editor from here, https://github.com/dig/onset-sandbox-editor

**Comment by LogicViper** [comment]
> Hi, you are using the old map editor which exports to ini/lua. My editor/world packages do not support the old format, we are json only. If you use the updated editor (which comes with the server by default), it will generate a world.json in the root server directory when the world is saved. You can download the editor from here, https://github.com/dig/onset-sandbox-editor

thank you also it dossent come with the server for some reason this is a new install and still got the old one but thnks this makes a lot of sense 

also nice fast responds

**Comment by dig** [comment]
Join the Onset discord for support. https://discordapp.com/invite/C8qSa2K

**Comment by LogicViper** [comment]
so i just need to replace the old sandbox with this one right
